### ISSUE TITLE
clip attention graph

### ISSUE THREAD

**Issue by dle666** [jyLin8100/GenSAM#1]
This is an excellent work and I am very much interested in the advanced effects of clip attention maps in it. 

Can you share the code used to generate the clip attention graph in the paper. 

Thank you very much.

**Comment by lwpyh** [comment]
> This is an excellent work and I am very much interested in the advanced effects of clip attention maps in it.
> 
> Can you share the code used to generate the clip attention graph in the paper.
> 
> Thank you very much.

Hi, thank you for your reply. Actually, you just need append code: "plt.imsave(save_path_dir + img_name + f'_maskLog{i}.jpg',  mask_logit_origin_l[i])" after line 170, then you can see the visualzation of our heatmap as follow.
Hope it can help you.

![animal-1_0](https://github.com/jyLin8100/GenSAM/assets/35630511/b6d01d24-09b6-494c-8528-99eb259d579f)
![animal-1_maskLog0](https://github.com/jyLin8100/GenSAM/assets/35630511/61d27821-2f0f-49b3-91b0-bed9a078169a)

**Comment by lwpyh** [comment]
> This is an excellent work and I am very much interested in the advanced effects of clip attention maps in it.
> 
> Can you share the code used to generate the clip attention graph in the paper.
> 
> Thank you very much.

Hi there, thanks for your question. You can find the utilis_model.py file and go to line 67. The variable sm_logit can be the Clip attention map you are looking for. You'll need to resize it to match the size of the input image and save it. We are planning to add visualization codes for the Clip attention maps in the near future.

**Comment by lwpyh** [comment]
> This is an excellent work and I am very much interested in the advanced effects of clip attention maps in it.
> 
> Can you share the code used to generate the clip attention graph in the paper.
> 
> Thank you very much.

Hi,

We have uploaded the demo, you can now play with the visualization by use it strightforwardly.
