### ISSUE TITLE
The dataset missing problem

### ISSUE THREAD

**Issue by sadatamit17** [jyLin8100/GenSAM#2]
Hei, Thanks for the instructions, the [CHAMELEON](https://www.polsl.pl/rau6/datasets/)
dataset is unavailable from the link. please provide a Google drive link.

**Comment by jyLin8100** [comment]
Hi, you can get the testing dataset from [here](https://drive.google.com/file/d/1QEGnP9O7HbN_2tH999O3HRIsErIVYalx/view). Thanks :)
