### ISSUE TITLE
IndexError: string index out of range

### ISSUE THREAD

**Issue by ycyinchao** [jyLin8100/GenSAM#5]
The error message is as follows:
![image](https://github.com/user-attachments/assets/b2276197-1913-4d26-8cd5-a5c0091a6daf)

Then we conducted debugging and found that in `utils_model.py` (line 470), the `outputs` obtained by `outputs = tokenizer.decode(output_ids[0, input_ids.shape[1]:]).strip()` is an empty string `''`, which led to the error on line 483. It is worth noting that the image used is the first image `animal-1.jpg` from the CHAMELEON dataset, as shown in the figure.

**Comment by jyLin8100** [comment]
Hi ycyinchao,

We haven't come up with the problem of empty "outputs". You can probably check whether the input of the model is correct? To do this, you may try using different input images. 

You may also begin with running [demo_v1.ipynb](https://github.com/jyLin8100/GenSAM/blob/main/demo_v1.ipynb) and see whether it is able to run correctly in your current environment. 

Thanks! Feel free to ask further questions : )
